### ISSUE TITLE
v3.0.1b6 -wlan not working stable

### ISSUE THREAD

**Issue by tp1de** [emsesp/EMS-ESP32#39] opened 2021-03-29 14:18 UTC
I justed tested v3.0.1b6 but wlan is not connecting stable. 
ESP32 is connecting for a couple of seconds to router/accesspoint then loosing connection and so on.
I loaded new fw by webui and then tested to flash new by usb. Same result.

I went back to v3.0.1b5 which works stable.

**Comment by proddy** [comment] 2021-03-29 14:39
ok thanks for reporting. I'll look into it

**Comment by MichaelDvP** [comment] 2021-03-29 16:17
@proddy seems to be the linkup() in mqttsettingsservice. (like in syslog, but no bootloop, only reconnect).

**Comment by proddy** [comment] 2021-03-29 17:29
Ah. So maybe start mqtt after network.

**Comment by proddy** [comment] 2021-03-29 18:12
I've reproduced it - working on a fix

**Comment by proddy** [comment] 2021-03-29 20:31
think its fixed now.

**Closed by proddy** 2021-03-29 20:31 UTC
Labels: bug

**Comment by tp1de** [comment] 2021-03-30 08:57
@proddy Yes I can confirm it's working again.
