### ISSUE TITLE
ESP32 EMS Connection Version 3.1

### ISSUE THREAD

**Issue by stmb-100** [emsesp/EMS-ESP32#72] opened 2021-06-11 15:23 UTC
Since version 3.1.0 I can no longer establish a stable connection with my EMS. The problem also exists with version v3.1.1b6
With the last 3.0.1 version everything still works stable.
TX-Mode = EMS, BusID = ServiceKey, TX Start delay = 2, Board Profile, BBQKees Gateway S32.

**Comment by proddy** [comment] 2021-06-11 17:32
that's not good. What happens exactly? Are you getting many Rx errors?

**Comment by stmb-100** [comment] 2021-06-11 17:56
![grafik](https://user-images.githubusercontent.com/54959405/121729657-01230980-caef-11eb-91f4-1cc41fe34a97.png)
![grafik](https://user-images.githubusercontent.com/54959405/121729809-2b74c700-caef-11eb-9af7-f155913a4e7b.png)

**Comment by stmb-100** [comment] 2021-06-11 17:58
![grafik](https://user-images.githubusercontent.com/54959405/121729940-54955780-caef-11eb-8455-a0c6f50ed98f.png)

**Comment by stmb-100** [comment] 2021-06-11 18:38
With Version 3.01

![grafik](https://user-images.githubusercontent.com/54959405/121734394-01be9e80-caf5-11eb-9f23-751dc00b1f70.png)

**Comment by proddy** [comment] 2021-06-12 08:22
Which board are you using? I suspect it's a problem with migration to 3.1 and the new Board Profiles. Go to the "EMS-ESP Help" tab and click "To export your system settings click here" and look at `System.tx_gpio`. This GPIO pin should match what you had before.

**Comment by stmb-100** [comment] 2021-06-12 16:24
The Board is a ESP32 WROOM.32 D1 Mini

blob:file:///4a05c4aa-9b87-4be6-9bfd-1b1738a84c96

**Comment by stmb-100** [comment] 2021-06-12 16:57
Version 3.1
  "Settings": {
    "tx_mode": 1,
    "ems_bus_id": 11,
    "syslog_enabled": false,
    "syslog_level": 3,
    "syslog_mark_interval": 0,
    "syslog_host": "",
    "syslog_port": 514,
    "master_thermostat": 0,
    "shower_timer": true,
    "shower_alert": false,
    "rx_gpio": 23,
    "tx_gpio": 5,
    "dallas_gpio": 18,
    "dallas_parasite": false,
    "led_gpio": 2,
    "hide_led": false,
    "notoken_api": true,
    "analog_enabled": true,
    "pbutton_gpio": 0,
    "board_profile": "S32"
  }
 
Version 3.0
  "Settings": {
    "tx_mode": 1,
    "ems_bus_id": 11,
    "syslog_enabled": false,
    "syslog_level": 3,
    "syslog_mark_interval": 0,
    "syslog_host": "",
    "syslog_port": 514,
    "master_thermostat": 0,
    "shower_timer": true,
    "shower_alert": true,
    "rx_gpio": 23,
    "tx_gpio": 5,
    "dallas_gpio": 18,
    "dallas_parasite": false,
    "led_gpio": 2,
    "hide_led": false,
    "api_enabled": true,
    "analog_enabled": true,
    "pbutton_gpio": 0,
    "board_profile": "S32"
  }

**Comment by proddy** [comment] 2021-06-12 19:41
that is strange, same settings. Although you should probably change your board profile to be "MH-ET Live D1 Mini" and see if that makes a difference.

**Comment by proddy** [comment] 2021-06-12 19:44
and if you're not using a KM200 set tx delay to 0

**Comment by MichaelDvP** [comment] 2021-06-13 09:04
The first picture makes me wonder. It shows 'bus connected' with 87 messages received, no errors and no messages sent.
- If there are no more messages received, the bus should show disconnected, there is a timeout for that. 
- Normally we get around 730 messages per minute on the bus (my statistics), which means the bus is online since a few seconds.
- It takes more than a few seconds to register the devices. 

So the pictures shows a normal state for a few seconds after reboot.
Is the emsesp constantly rebooting? What does the uptime show?

**Comment by stmb-100** [comment] 2021-06-14 07:49
Hello it looks like the system does a reboot every 10-20 seconds. How can I activate a debug mode?

**Comment by stmb-100** [comment] 2021-06-14 07:56
![grafik](https://user-images.githubusercontent.com/54959405/121858360-d86d6080-ccf6-11eb-8236-78d6a13d0ef0.png)

**Comment by proddy** [comment] 2021-06-14 08:22
We need to find what is causing the crashes. Take out the ESP32, connect it via USB to a PC and then open a serial connection to the COM port using ptty or something similar. See the logs come in and see if it still crashes. If not then it's something to do with the EMS data coming in. While still connected to the PC go to the Web UI and disable MQTT, SysLog, NTP just to isolate those from being a possible root cause. Now connect the ESP32 back into the Gateway circuit. If possible keep the USB connected so you can see the log data coming in.

Just to be sure, it worked fine on 3.0 but crashes on 3.1?

**Comment by MichaelDvP** [comment] 2021-06-14 08:52
It seems to me there is something wrong with filesystem. It shows 320k, but we have 64k since 3.0.0b3 and before 192k (afair). 
Does it help to do a factory reset and reconfigure? 
@stmb-100 Do you have experience with flashing via usb/esptool?

**Comment by stmb-100** [comment] 2021-06-14 09:00
yes 3.0 no Problems.

It may be a problem with the power supply. The V 3.1 requires more power. On PC-USB I already have an UpTime of 8 minutes 

![grafik](https://user-images.githubusercontent.com/54959405/121866845-9d235f80-ccff-11eb-94f2-6b204f7b621f.png)

**Comment by stmb-100** [comment] 2021-06-14 09:01
Do you have experience with flashing via usb/esptool?
Yes i flashed with this tool.

**Comment by MichaelDvP** [comment] 2021-06-14 09:37
> Yes i flashed with this tool.

Because of the wrong partiition table i suggest a complete flash with partitioning and erase as described in the wiki:
`esptool.py --chip esp32 --port "COM3" --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x1000 bootloader_dio_40m.bin 0x8000 partitions.bin 0xe000 boot_app0.bin 0x10000 <firmware.bin>`
and add `-e` or `--erase-all` option.

**Comment by stmb-100** [comment] 2021-06-14 13:17
I reflash the ESP32
![grafik](https://user-images.githubusercontent.com/54959405/121898284-855dd280-cd23-11eb-8de9-1d3cb957fa33.png)

**Comment by stmb-100** [comment] 2021-06-14 14:08
It's really a power problem. Does not work with USB power supplies up to 5 V 2 A, only with PC-USB. Strange behavior with version 3.1

**Comment by stmb-100** [comment] 2021-06-14 14:19
blob:file:///3f5adb16-67ba-4b4b-abfd-59d52391f730

**Comment by MichaelDvP** [comment] 2021-06-14 14:21
Some usb-chargers are only chargers with large rippe, that needs the battery on the output for smoothing the voltage. They can not be used as power supply. Try another one or use the jack-power.  ESP32 works good with jack-power.

**Comment by stmb-100** [comment] 2021-06-14 14:26
If I take the USB supply from a raspberry Pi, the problem is the same.

**Comment by MichaelDvP** [comment] 2021-06-14 14:39
The soldering on GND and 5V dont look good. Is it a contact issue? 
BTW: the filesystem shows now 192k, have you flashed the 3.0 first via usb and updated OTA to v3.1. The actual partition table should give 64k filesystem and a 64k more flash for code and ota.

**Comment by stmb-100** [comment] 2021-06-14 14:51
![WhatsApp Image 2021-06-14 at 16 44 09 (1)](https://user-images.githubusercontent.com/54959405/121911375-015e1780-cd30-11eb-9231-eee2bcc76496.jpeg)

It doesn't work with Jack Power, if I add PC-USB it works again. 
I will re-solder and use a new ESP32 D1 Mini
First I flashed it with the Windows Flasher (ESP-Flasher-Windows-x64)

**Comment by MichaelDvP** [comment] 2021-06-14 15:08
I have a very similar configuration and it works with jackpower (Gateway 1.5, MH-ET32, GB125, RC35, MM10, SM10), i think you should resolder the lower two pins on right side (GND/5V) and try again with jack-power.

**Comment by MichaelDvP** [comment] 2021-06-14 15:19
> First I flashed it with the Windows Flasher (ESP-Flasher-Windows-x64)

Ah, that's why i ask for esptool. Most GUI-flashers do not partition correctly.

**Comment by stmb-100** [comment] 2021-06-14 21:27
I have now plugged the jack cable directly into the heater, without a 10 meter extension and now the connection works via jack power supply with V 3.1 and also with the USB power supply. The fault was the 10 meter extension of the jack connection.

**Comment by proddy** [comment] 2021-06-15 11:13
right, so false alarm. Do you want to close this issue?

**Comment by bbqkees** [comment] 2021-06-18 09:04
Jack cables are usually intended for audio signals, the wires inside are very thin and cheap and may give powering issues when used with the Gateway. You may lose several volts over that 10m cable, and intorduce other interferences in the EMS signal.

The jack cable that is supplied with the Gateway therefore has thicker copper wires inside.

**Closed** 2021-06-29 05:58 UTC
Labels: bug
