### ISSUE TITLE
EMS-ESP-3_5_0b2 - HA Discovery not working

### ISSUE THREAD

**Issue by zibous** [emsesp/EMS-ESP32#634] opened 2022-09-23 07:23 UTC
**Bug description**
Version v3.4.2b5 is working.

After installing the new version, wrong topic entries are made at HA Discovery. 
Some are correct but most are created under the `hostname of the device`  
and the i can`nt see any EMS ESP Devices.

**Steps to reproduce**
1. Delete all HA Discovery Items
2. Install Version EMS-ESP-3_5_0b2
3. Check HA Devices EMS_ESP

**Screenshots**

![Bildschirmfoto 2022-09-22 um 19 10 13](https://user-images.githubusercontent.com/30198737/191909896-1a230d84-de9e-4e74-ac12-90e14cf7863b.png)

**Device information**
[emsesp_info.txt](https://github.com/emsesp/EMS-ESP32/files/9631479/emsesp_info.txt)

**Comment by MichaelDvP** [comment] 2022-09-23 08:49
I think this is #596. But the commit only addresses ems entities, dallas/analog follows the old scheme. 
As far as i understand (i'm not using ha) the config is now generated as `homeassistant/sensor/hostname/entity/config` with `"~":base, "stat_t":"~/device_data"` and entities are published in `base/device_data`. 
What exactly is not working?

**Comment by zibous** [comment] 2022-09-23 09:37
> What exactly is not working?

Previous Version - shows devices:

![Bildschirmfoto 2022-09-23 um 11 13 20](https://user-images.githubusercontent.com/30198737/191931566-29293af3-a1fe-425a-ae95-3e3d17d55143.png)


1. Remove all ems-esp devices form Homeassistant
2. Remove all items for MQTT Brocker homeassistant/ems-heizung

Install version EMS-ESP-3_5_0b2

Result:
EMS-ESP-3_5_0b2 - No EMS-ESP Devices found
![Bildschirmfoto 2022-09-23 um 11 29 23](https://user-images.githubusercontent.com/30198737/191931901-6acf273a-0889-4cb4-9054-664ea566b823.png)


Switch back to Firmware: v3.4.2b5
All devices are present and working.

**Comment by proddy** [comment] 2022-09-23 16:33
I'm back behind a PC now and have reproduced this. If you use a FQDN as the hostname it doesn't work. Thomas was also complaining on Discord about this. The best solution is to create a new option in the MQTT Settings called 'prefix' or something which we'll use as prefix instead of base or hostname. https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic

**Comment by MichaelDvP** [comment] 2022-09-23 16:51
Could we keep it mostly compatible to v3.4.2 and use the base for discover node-id, but replace possible slashes by underscore. e.g base `emsesp`  keeps as is, but base: `home/esp/emsesp` as in #596 is set as `homeassistant/sensor/home_ems_emsesp/name/config`. Most users have a single base, so there is no change.
Maybe this could also used as prefix for entities. Is this prefix realy needed?

**Comment by zibous** [comment] 2022-09-23 16:52
@proddy 
> The best solution is to create a new option in the MQTT Settings called 'prefix' or something which we'll use as prefix instead of base or hostname. https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic

I can not find the `prefix` for the MQTT Settings, only  `discovery_prefix string (Optional, default: homeassistant)`, which I cannot change, because otherwise all other devices will no longer work.

**Comment by MichaelDvP** [comment] 2022-09-23 17:06
@zibous : This is a prefix proddy added to `object_id` to make it more unique. [see here](https://github.com/emsesp/EMS-ESP32/blob/12638275faa6c3f20f53d8d50d1e0b0b1bd1fd6c/src/mqtt.cpp#L1131)

**Comment by proddy** [comment] 2022-09-23 18:45
> Could we keep it mostly compatible to v3.4.2 and use the base for discover node-id, but replace possible slashes by underscore. e.g base `emsesp` keeps as is, but base: `home/esp/emsesp` as in #596 is set as `homeassistant/sensor/home_ems_emsesp/name/config`. Most users have a single base, so there is no change. Maybe this could also used as prefix for entities. Is this prefix realy needed?

that would work. Replace . with _ using the base. Shall I make the change?

**Comment by MichaelDvP** [comment] 2022-09-23 19:07
As you like. I've already started a test, so it's half way implemented here. But i can't test with HA. 
This is how it looks like with base `ems/esp`
![grafik](https://user-images.githubusercontent.com/59284019/192039667-08cde3f0-aebc-4a3f-80c9-9923ae6dc62f.png)
Mainly in load_settings set:
```
    // create basename from base
    mqtt_basename_ = mqtt_base_;
    std::replace(mqtt_basename_.begin(), mqtt_basename_.end(), '/', '_');
```
and use `mqtt_basename_` instead of `system_hostname_` everywhere.

**Comment by proddy** [comment] 2022-09-23 19:09
looks good. I can test it from your repo. I have a project setup in VSC that pulls from your dev

**Comment by MichaelDvP** [comment] 2022-09-23 19:50
Ok, just added analog/dallas, now compiling, will push in a few minutes to my repo.

**Comment by zibous** [comment] 2022-09-25 06:15
@proddy 

I think the problem is:

><object_id>: The ID of the device. This is only to allow for separate topics for each device and is not used for the entity_id. The ID of the device must only consist of characters from the character class [a-zA-Z0-9_-] (alphanumerics, underscore and hyphen).

`"object_id": "ems-heizung.siebler.home_system_NTP status"`

I my case the object_id is not valid.  Why not slugify the objec_id value  `ems-heizungsieblerhomesystemntp-status` ?

see: https://slugify.online/

**Comment by MichaelDvP** [comment] 2022-09-25 06:39
HA documentation and namings are also confusing to me. There is a [object_id](https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic) in the discovery topic with naming restrictions and this is not the entity. And there is an [object_id](https://www.home-assistant.io/docs/mqtt/discovery/#use-object_id-to-influence-the-entity-id) in payload, this is entity and allows whitespace, etc.
Now we have the topic-node id as a single word base, topic-object_id as `device_shortname` as before and payload object_id without prefix as `device_EN-name` (as in v3.4). Have you tried the new dev?

**Comment by proddy** [comment] 2022-09-25 06:46
@zibous try the latest dev. Michael has fixed this. The object_id and names are no longer prefixed

**Comment by zibous** [comment] 2022-09-25 07:03
> HA documentation and namings are also confusing to me.
Yes me too...

> Have you tried the new dev?
sorry now testing Firmware: v3.5.0b3  and it works.

Thanks.

**Comment by proddy** [comment] 2022-09-25 08:41
great. closing. do re-open if you find an issue

**Closed by proddy** 2022-09-25 08:41 UTC
Labels: bug
