### ISSUE TITLE
Improvement: Add holiday mode to bosch compress 3800i ew

### ISSUE THREAD

**Issue by mattfro** [emsesp/EMS-ESP32#1735] opened 2024-05-03 10:02 UTC
### PROBLEM DESCRIPTION

Can't find holiday "mode"

### REQUESTED INFORMATION

{
  "System Info": {
    "version": "3.7.0-dev.8",
    "uptime": "000+01:07:15.548",
    "uptime (seconds)": 4035,
    "platform": "ESP32-S3",
    "arduino": "ESP32 Arduino v2.0.14",
    "sdk": "v4.4.6-dirty",
    "free mem": 193,
    "max alloc": 183,
    "free caps": 8330,
    "used app": 2165,
    "free app": 5963,
    "partition": "app1",
    "reset reason": "Software reset CPU / Software reset CPU"
  },
  "Network Info": {
    "network": "WiFi",
    "hostname": "ems-esp",
    "RSSI": -54,
    "TxPower setting": 0,
    "static ip config": false,
    "enable IPv6": false,
    "low bandwidth": false,
    "disable sleep": false,
    "enable MDNS": true,
    "enable CORS": false,
    "AP provision mode": "disconnected",
    "AP security": "wpa2",
    "AP ssid": "ems-esp"
  },
  "NTP Info": {
    "NTP status": "connected",
    "enabled": true,
    "server": "time.google.com",
    "tz label": "Europe/Stockholm"
  },
  "OTA Info": {
    "enabled": false,
    "port": 8266
  },
  "MQTT Info": {
    "MQTT status": "connected",
    "MQTT publishes": 1307,
    "MQTT queued": 0,
    "MQTT publish fails": 0,
    "MQTT connects": 1,
    "enabled": true,
    "client id": "esp32-463bdaec",
    "keep alive": 60,
    "clean session": false,
    "entity format": 0,
    "base": "ems-esp",
    "discovery prefix": "homeassistant",
    "discovery type": 0,
    "nested format": 1,
    "ha enabled": true,
    "mqtt qos": 0,
    "mqtt retain": false,
    "publish time heartbeat": 60,
    "publish time boiler": 10,
    "publish time thermostat": 10,
    "publish time solar": 10,
    "publish time mixer": 10,
    "publish time water": 10,
    "publish time other": 10,
    "publish time sensor": 10,
    "publish single": false,
    "publish2command": false,
    "send response": false
  },
  "Syslog Info": {
    "enabled": false
  },
  "Sensor Info": {
    "temperature sensors": 0,
    "temperature sensor reads": 0,
    "temperature sensor fails": 0
  },
  "API Info": {
    "API calls": 4,
    "API fails": 0
  },
  "Bus Info": {
    "bus status": "connected",
    "bus protocol": "HT3",
    "bus telegrams received (rx)": 20839,
    "bus reads (tx)": 2785,
    "bus writes (tx)": 2,
    "bus incomplete telegrams": 6,
    "bus reads failed": 0,
    "bus writes failed": 0,
    "bus rx line quality": 100,
    "bus tx line quality": 100
  },
  "Settings": {
    "board profile": "S32S3",
    "locale": "en",
    "tx mode": 2,
    "ems bus id": 11,
    "shower timer": false,
    "shower alert": false,
    "hide led": false,
    "notoken api": false,
    "readonly mode": false,
    "fahrenheit": false,
    "dallas parasite": false,
    "bool format": 1,
    "bool dashboard": 1,
    "enum format": 1,
    "analog enabled": false,
    "telnet enabled": true,
    "max web log buffer": 50,
    "web log buffer": 33
  },
  "Devices": [
    {
      "type": "boiler",
      "name": "Enviline/Compress 6000AW/Hybrid 3000-7000iAW/SupraEco/Geo 5xx/WLW196i/WSW196i",
      "device id": "0x08",
      "product id": 172,
      "version": "03.01",
      "entities": 114,
      "handlers received": "0xBF 0xC2 0xD1 0xE3 0xE4 0xE5 0xE9 0x0494 0x0495 0x048F",
      "handlers fetched": "0x14 0xE6 0xEA 0x048D 0x048A 0x04A2 0x0485 0x0492 0x0488 0x0484 0x048B 0x0491 0x0499 0x049C 0x049D 0x02CC 0x04A5",
      "handlers pending": "0x10 0x11 0x15 0x1C 0x18 0x19 0x1A 0x35 0x16 0x33 0x34 0x26 0x2A 0x28 0x0486 0x04AE 0x04AF",
      "handlers ignored": "0x049F 0x04A0 0x04A3 0xF7 0x0497"
    },
    {
      "type": "thermostat",
      "name": "Rego 2000/3000",
      "device id": "0x10",
      "product id": 172,
      "version": "03.01",
      "entities": 50,
      "handlers received": "0x06 0x031D",
      "handlers fetched": "0x02A5 0x02B9 0x02AF 0x029B 0x0471 0x02A6 0x02BA 0x02B0 0x029C 0x0472 0x0467 0x0291 0x0468 0x0292 0x02F5 0x023A 0x0240",
      "handlers pending": "0xA3 0xA2 0x12 0x13 0x02A7 0x02BB 0x02B1 0x029D 0x0473 0x02A8 0x02BC 0x02B2 0x029E 0x0474 0x02A9 0x02BD 0x02B3 0x029F 0x0475 0x02AA 0x02BE 0x02B4 0x02A0 0x0476 0x02AB 0x02BF 0x02B5 0x02A1 0x0477 0x02AC 0x02C0 0x02B6 0x02A2 0x0478 0x02CC 0x02CE 0x02D0 0x0469 0x0293 0x02D2 0x046A 0x0294 0x02F6 0x031B",
      "handlers ignored": "0x042B 0xF7 0x0269"
    },
    {
      "type": "thermostat",
      "name": "RC200/CW100",
      "device id": "0x38",
      "product id": 157,
      "version": "32.02",
      "entities": 1,
      "handlers received": "0x042B"
    },
    {
      "type": "gateway",
      "name": "KM200/MB LAN 2",
      "device id": "0x48",
      "product id": 189,
      "version": "04.08",
      "entities": 0,
      "handlers ignored": "0xF9 0x0484 0x0269"
    },
    {
      "type": "controller",
      "name": "Rego 3000",
      "device id": "0x09",
      "product id": 240,
      "version": "38.03",
      "entities": 1,
      "handlers received": "0x06",
      "handlers ignored": "0xBF 0x0269"
    }
  ]
}

I think I managed to find when you set the date in ems logs:
**000+00:50:30.130 T 1356: [emsesp] gateway(0x48) -W-> thermostat(0x10), ?(0x0269), data: 18 05 03 18 05 05**

Holiday 03.05.2024 to 05.05.2024
############################
000+00:50:27.139 T 1351: [emsesp] gateway(0x48) -R-> boiler(0x08), ValueConfig(0xF9), length: 17, data: EA 00 00 12
000+00:50:27.176 T 1352: [emsesp] boiler(0x08) -W-> gateway(0x48), ValueConfig(0xF9), data: EA 00 00 12 07 00 00 00 28 00 00 00 2A 00 00 00 34 00 00 00 2A
000+00:50:27.715 T 1353: [emsesp] gateway(0x48) -R-> boiler(0x08), ValueConfig(0xF9), length: 17, data: EA 00 00 06
000+00:50:27.751 T 1354: [emsesp] boiler(0x08) -W-> gateway(0x48), ValueConfig(0xF9), data: EA 00 00 06 07 00 00 00 28 00 00 00 36 00 00 00 39 00 00 00 36
000+00:50:27.975 T 1355: [emsesp] controller(0x09) -B-> All(0x00), RCTime(0x06), data: 18 05 0B 03 28 17 04 01 09 FF 00
**000+00:50:30.130 T 1356: [emsesp] gateway(0x48) -W-> thermostat(0x10), ?(0x0269), data: 18 05 03 18 05 05**
000+00:50:30.890 T 1357: [emsesp] thermostat(0x10) -B-> All(0x00), ?(0x0269), data: 18 05 03 18 05 05 02 11
000+00:50:31.094 T 1358: [emsesp] boiler(0x08) -B-> All(0x00), UBAMonitorFastPlus(0xE4), data: 10 20 30 48 00 CB 00 00 D6 00 00 00 00 02 B2 00 00 00 EB 00 00 00 00 01 AC 00 D6
000+00:50:31.282 T 1359: [emsesp] boiler(0x08) -B-> All(0x00), UBAMonitorSlowPlus2(0xE3), data: 04 00 00 00 00 00 00 00 00 00 00 00 D6 00 00 55
000+00:50:31.479 T 1360: [emsesp] boiler(0x08) -B-> All(0x00), UBAMonitorWWPlus(0xE9), data: 39 01 E3 01 D8 00 00 00 00 41 3C 00 00 05 00 00 00 00 00 00 00 00 00 39
000+00:50:31.726 T 1361: [emsesp] thermostat(0x38) -W-> thermostat(0x10), RemoteTemp(0x042B), data: 00 EA 09 27 01
000+00:50:31.987 T 1362: [emsesp] boiler(0x08) -B-> All(0x00), ?(0x049F), data: 00 00 00 00 00 00 00 00 07 08 00 00 00 00 00 96 00 00
000+00:50:32.171 T 1363: [emsesp] boiler(0x08) -B-> All(0x00), ?(0x04A0), data: 00 00 00 00
000+00:50:32.368 T 1364: [emsesp] boiler(0x08) -B-> All(0x00), ?(0x04A3), data: 00 01 00 00 00 00 00 00 00 00 00 09 00 00 00 00 00 00 00 00 08 00 00 00

Reset holiday, not really sure what happens here:
############################
000+00:51:10.445 T 1406: [emsesp] thermostat(0x10) -W-> Me(0x0B), RC300Summer(0x02B0), data: 28 00 00 37 23 00 00 16 1E 00 00 00 16 (offset 1)
000+00:51:10.668 T 1407: [emsesp] Me(0x0B) -R-> thermostat(0x10), RC300Curves(0x029C), length: 25
000+00:51:10.689 T 1408: [emsesp] thermostat(0x10) -W-> Me(0x0B), RC300Curves(0x029C), data: 01 00 00 00 03 05 23 37 (offset 1)
000+00:51:10.944 T 1409: [emsesp] boiler(0x08) -B-> All(0x00), UBAMonitorFastPlus(0xE4), data: 10 20 30 48 00 CB 00 00 D6 00 00 00 00 02 B2 00 00 00 EB 00 00 00 00 01 AC 00 D6
000+00:51:11.121 T 1410: [emsesp] boiler(0x08) -B-> All(0x00), MenuConfig(0xF7), data: D1 00 00 07
000+00:51:11.308 T 1411: [emsesp] boiler(0x08) -B-> All(0x00), UBAMonitorSlowPlus2(0xE3), data: 04 00 00 00 00 00 00 00 00 00 00 00 D6 00 00 55
000+00:51:11.504 T 1412: [emsesp] boiler(0x08) -B-> All(0x00), UBAMonitorWWPlus(0xE9), data: 39 01 E3 01 D8 00 00 00 00 41 3C 00 00 05 00 00 00 00 00 00 00 00 00 39
000+00:51:11.700 T 1413: [emsesp] boiler(0x08) -B-> All(0x00), ?(0x049F), data: 00 00 00 00 00 00 00 00 07 08 00 00 00 00 00 96 00 00
000+00:51:11.887 T 1414: [emsesp] boiler(0x08) -B-> All(0x00), ?(0x04A0), data: 00 00 00 00
000+00:51:12.156 T 1415: [emsesp] Me(0x0B) -R-> thermostat(0x10), RC300Summer2(0x0472), length: 25
000+00:51:12.177 T 1416: [emsesp] thermostat(0x10) -W-> Me(0x0B), RC300Summer2(0x0472), data: 01 12 03 03 03 14 06 04
000+00:51:12.219 T 1417: [emsesp] boiler(0x08) -B-> All(0x00), ?(0x04A3), data: 00 01 00 00 00 00 00 00 00 00 00 09 00 00 00 00 00 00 00 00 08 00 00 00
000+00:51:12.569 T 1418: [emsesp] gateway(0x48) -R-> boiler(0x08), UBAMonitorFastPlus(0xE4), length: 1 (offset 40)
000+00:51:12.579 T 1419: [emsesp] boiler(0x08) -W-> gateway(0x48), UBAMonitorFastPlus(0xE4), data: <empty> (offset 40)
000+00:51:12.616 T 1420: [emsesp] gateway(0x48) -W-> thermostat(0x10), ?(0x0269), data: 09 01 01 09 01 01
000+00:51:12.706 T 1421: [emsesp] Me(0x0B) -R-> thermostat(0x10), HPSet(0x0467), length: 25
000+00:51:12.724 T 1422: [emsesp] thermostat(0x10) -W-> Me(0x0B), HPSet(0x0467), data: 12 18 00 01 02
000+00:51:12.908 T 1423: [emsesp] boiler(0x08) -B-> All(0x00), MenuConfig(0xF7), data: D1 00 00 07
000+00:51:13.168 T 1424: [emsesp] Me(0x0B) -R-> thermostat(0x10), HPMode(0x0291), length: 25
000+00:51:13.186 T 1425: [emsesp] thermostat(0x10) -W-> Me(0x0B), HPMode(0x0291), data: 01 00 00 00 00 00
000+00:51:13.214 T 1426: [emsesp] thermostat(0x10) -B-> All(0x00), ?(0x0269), data: 09 01 01 09 01 01 02 11
000+00:51:13.473 T 1427: [emsesp] controller(0x09) -W-> thermostat(0x10), ?(0x0269), data: 12 01 01 12 01 01 00 11
000+00:51:13.569 T 1428: [emsesp] gateway(0x48) -R-> boiler(0x08), ?(0x04), length: 2 (offset 25)
000+00:51:13.579 T 1429: [emsesp] boiler(0x08) -W-> gateway(0x48), ?(0x04), data: <empty> (offset 25)
000+00:51:13.643 T 1430: [emsesp] Me(0x0B) -R-> thermostat(0x10), HPSet(0x0468), length: 25
000+00:51:13.660 T 1431: [emsesp] thermostat(0x10) -W-> Me(0x0B), HPSet(0x0468), data: 12 18 00 01 02
000+00:51:13.931 T 1432: [emsesp] Me(0x0B) -R-> thermostat(0x10), HPMode(0x0292), length: 25
000+00:51:13.950 T 1433: [emsesp] thermostat(0x10) -W-> Me(0x0B), HPMode(0x0292), data: 00 00 00 00 00 00
000+00:51:13.984 T 1434: [emsesp] controller(0x09) -R-> thermostat(0x10), ?(0x0269), length: 8
000+00:51:14.001 T 1435: [emsesp] thermostat(0x10) -W-> controller(0x09), ?(0x0269), data: 12 01 01 12 01 01 02 11
000+00:51:14.051 T 1436: [emsesp] thermostat(0x10) -B-> All(0x00), ?(0x0269), data: 12 01 01 12 01 01 02 11
000+00:51:14.443 T 1437: [emsesp] Me(0x0B) -R-> thermostat(0x10), RC300WWmode(0x02F5), length: 25
000+00:51:14.480 T 1438: [emsesp] thermostat(0x10) -W-> Me(0x0B), RC300WWmode(0x02F5), data: 01 00 05 00 00 FF 08 06 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00
000+00:51:14.693 T 1439: [emsesp] Me(0x0B) -R-> thermostat(0x10), RC300OutdoorTemp(0x023A), length: 25
000+00:51:14.707 T 1440: [emsesp] thermostat(0x10) -W-> Me(0x0B), RC300OutdoorTemp(0x023A), data: 00 AC
000+00:51:14.981 T 1441: [emsesp] Me(0x0B) -R-> thermostat(0x10), RC300Settings(0x0240), length: 25
000+00:51:14.999 T 1442: [emsesp] thermostat(0x10) -W-> Me(0x0B), RC300Settings(0x0240), data: 00 01 EC 00 FF (offset 8)

**Comment by MichaelDvP** [comment] 2024-05-03 10:56
See #275, the next bytes are heating mode,temperature,  dhw mode, and assign to hc/dhw circuits and this for 5 holiday entries.
All in all its 50-75 entities, depending what info we combine. Too much for RAM and mqtt-heap usage.
RC300 switchprograms and holiday settings are often discussed, but in the actual data structure is not easy to implement. 
And this are settings very rarly changed.

**Comment by mattfro** [comment] 2024-05-03 11:40
Ok I see...
But couldn't it be that if you set that date then rest will be set automatically?
Because, only parameter I can set in the pump for holiday is, a start date end date.
And if I want to turn it off, it's just reset.

Seems in holiday mode, it's set to fixed 17C.

But according to that ticket it seems not to be the case... Oh well, was hoping it would be a easy thing :)
Anyways, I could do my own "holiday/vacation" setup instead in hass.  Just lower the temperature and some other small tunings like warm water etc.

**Comment by MichaelDvP** [comment] 2024-05-03 12:06
Yes, seems to be a shortend telegram. 
`thermostat(0x10) -B-> All(0x00), ?(0x0269), data: 18 05 03 18 05 05 02 11`
means 03.05.2024-05.05.2024, fixed temperature mode (02), 17°C 
Can you check in terminal `read 8 269`, `read 8 26A`, ... `read 8 26D` to check the length and if there are also 5 dates.
It seems the the info to heatingcircuits and dhw are missing in this telegram,  Do this setting affect dhw or is there a additional setting?

**Comment by mattfro** [comment] 2024-05-03 12:27
@MichaelDvP read 8? or read 10 269
If I do read 8 269, 26A and 26D it's always empty
ems-esp:# read 8 269
000+03:23:26.362 N 81: [emsesp] boiler(0x08) -W-> Me(0x0B), ?(0x0269), data: <empty>
ems-esp:# read 8 26A
000+03:23:34.434 N 82: [emsesp] boiler(0x08) -W-> Me(0x0B), ?(0x026A), data: <empty>
ems-esp:# read 8 26D
000+03:23:42.745 N 83: [emsesp] boiler(0x08) -W-> Me(0x0B), ?(0x026D), data: <empty>

if I check read 10 before I set vacation:
ems-esp:#  read 10 269
000+03:34:16.485 N 89: [emsesp] thermostat(0x10) -W-> Me(0x0B), ?(0x0269), data: 12 01 01 12 01 01 02 11
ems-esp:#  read 10 26A
000+03:35:34.816 N 90: [emsesp] thermostat(0x10) -W-> Me(0x0B), ?(0x026A), data: <empty>
ems-esp:#  read 10 26D
000+03:35:45.216 N 91: [emsesp] thermostat(0x10) -W-> Me(0x0B), ?(0x026D), data: <empty>

and this is when I set vacation:
ems-esp:#  read 10 269
000+03:36:15.699 N 92: [emsesp] thermostat(0x10) -W-> Me(0x0B), ?(0x0269), data: 18 05 03 18 05 05 02 11
ems-esp:#  read 10 26A
000+03:36:19.829 N 93: [emsesp] thermostat(0x10) -W-> Me(0x0B), ?(0x026A), data: <empty>
ems-esp:#  read 10 26D
000+03:36:22.929 N 94: [emsesp] thermostat(0x10) -W-> Me(0x0B), ?(0x026D), data: <empty>

**Comment by mattfro** [comment] 2024-05-03 12:52
btw. when I took the logs for setting vacation in the first place, I used my phone app, so you can see it comes from the gateway 0x48.

Tried again using the app and set date:
000+03:57:56.335 N 309: [emsesp] gateway(0x48) -W-> thermostat(0x10), ?(0x0269), data: 18 05 03 18 05 05

and when doing reset or removing the date:
000+03:58:22.886 N 312: [emsesp] gateway(0x48) -W-> thermostat(0x10), ?(0x0269), data: 09 01 01 09 01 01

not sure if that helps... I wonder if you could test to use that as a custom entity to try to see if it would work. Set only those?

**Comment by MichaelDvP** [comment] 2024-05-03 15:21
> read 8? or read 10 269

Youre right, read from thermostat 0x10. 
Funny communication, the gateway sets 01.01.2009 as off, and the controller (0x09) corrects to 01.01.2018. But i think we can write any date in the past.
I'll add a single entity for the rego thermostat, only dates as for RC35/RC30.

**Comment by MichaelDvP** [comment] 2024-05-04 08:04
Have you already tested if you can change the holiday temperature with custom entity:
device 0x10, type 0x0269, offset 7,factor 1

**Comment by mattfro** [comment] 2024-05-04 08:38
@MichaelDvP Oh... I think we got a misunderstanding here :)
I thought you where going to add it in the next build...
So... I did not test that,.

I have a few question in this case
![image](https://github.com/emsesp/EMS-ESP32/assets/46936922/7af30d5a-ce7e-4ddd-a318-1ca0743f74d5)
should I use int8?

And how should the value be sent, what format?
![image](https://github.com/emsesp/EMS-ESP32/assets/46936922/c409a03e-2b41-4ab7-a1e2-de19f02e886d)

**Comment by MichaelDvP** [comment] 2024-05-04 09:24
>I thought you where going to add it in the next build...

Yes,the dates, for temperature i'm not sure because you wrote  
> Seems in holiday mode, it's set to fixed 17C.

this value range int8 and uint8 is the same, does not matter. It takes a minute until the value show up. 
Just enter a temperature different from 17 maybe 15 or 18 degrees and check if it changes, You can log the telegrams while changing to see the protocol. Maybe the controller overwrite like the off-dates.

**Comment by mattfro** [comment] 2024-05-04 09:35
I meant in what format should I send the value in?
Raw or as a date?
18 05 04 18 05 05 or 240504240505
and why does it have a value 17?
![image](https://github.com/emsesp/EMS-ESP32/assets/46936922/89d8910a-4cd5-4701-958c-bdb03bab892a)

Is it correct offset?

**Comment by mattfro** [comment] 2024-05-04 09:44
oh are you saying latest build has already holiday in it?
I have latest.. and I don't have any holiday or vacation settings. Only date settings is the "normal" one.

**Comment by MichaelDvP** [comment] 2024-05-04 09:58
I'm working on it, it's not yet implemented. If you like to use custom entitiy its:
`holidaydate`: device 0x10, type 0x269, offset 0, type RAW, length 6 with data `18 05 04 18 05 05`
`holidaytemp` device 0x10, type 0x269, offset 7, type UINT8, UOM °C with data `17`

**Comment by mattfro** [comment] 2024-05-04 10:37
Did not try holiday temp... 
But otherwise it worked fine, checked both the pump UI and phone app, it was on holiday mode when setting that value.
Also I did reset it with these values, as the app used to send: 09 01 01 09 01 01

So for my point of view it works fine what I could see...attached logs for this also.
[holiday.log](https://github.com/emsesp/EMS-ESP32/files/15209406/holiday.log)

activated holiday:
ems-esp:# 000+20:31:07.685 I 133: [command] Calling command 'custom/holiday' (set custom value on ems) with value 18 05 04 18 05 05

reset holiday:
ems-esp:# 000+20:33:11.683 I 761: [command] Calling command 'custom/holiday' (set custom value on ems) with value 09 01 01 09 01 01
later on it changes to this:
ems-esp:# 000+20:33:13.840 T 785: [emsesp] controller(0x09) -W-> thermostat(0x10), ?(0x0269), data: 12 01 01 12 01 01 00 11

**Comment by mattfro** [comment] 2024-05-04 10:41
And also, I don't see any point of changing the holiday temp to anything else than 17. According to the manual, you should not set it under 17C anyways. The heatpump would not work under those temperatures...at least in a way it would save any energy.

**Comment by MichaelDvP** [comment] 2024-05-04 11:12
Please check dev9: https://github.com/MichaelDvP/EMS-ESP32/releases

**Comment by mattfro** [comment] 2024-05-04 11:21
@MichaelDvP tried it already:
![image](https://github.com/emsesp/EMS-ESP32/assets/46936922/da93b680-0fc7-4003-ad2e-c4e6ca19c6af)
maybe fix the name :)
and it's setting the year wrong:
000+00:15:07.115 T 76: [emsesp] thermostat(0x10) -W-> gateway(0x48), ?(0x026A), data: <empty> (offset 4)
**000+00:15:07.125 I 77: [command] Calling command 'thermostat/holiday' (Urlaub) with value 04.05.2014-05.05.2014**
000+00:15:07.213 T 78: [emsesp] Me(0x0B) -W-> thermostat(0x10), RC300Holiday1(0x0269), data: 04 05 0E 05 05 0E
000+00:15:07.393 T 79: [emsesp] gateway(0x48) -R-> thermostat(0x10), ?(0x026B), length: 1
000+00:15:07.403 T 80: [emsesp] thermostat(0x10) -W-> gateway(0x48), ?(0x026B), data: <empty>

year first, then month and day. I think

**Comment by MichaelDvP** [comment] 2024-05-04 11:40
Oh, sorry, yes, Bosch changes the order for RC30/RC35 and RC300/Rego, Updated my dev.

**Comment by mattfro** [comment] 2024-05-04 11:57
@MichaelDvP 
works fine now:
000+00:04:25.565 I 27: [command] Calling command 'thermostat/vacations' (vacation dates) with value 04.05.2024-05.05.2024
000+00:04:25.604 T 28: [emsesp] Me(0x0B) -W-> thermostat(0x10), RC300Holiday1(0x0269), data: 18 05 04 18 05 05

and setting date to yesterday to reset it:
000+00:05:35.523 I 76: [command] Calling command 'thermostat/vacations' (vacation dates) with value 02.05.2024-02.05.2024
000+00:05:35.859 T 88: [emsesp] Me(0x0B) -W-> thermostat(0x10), RC300Holiday1(0x0269), data: 18 05 02 18 05 02
000+00:05:36.067 T 89: [emsesp] Me(0x0B) -R-> thermostat(0x10), RC300Holiday1(0x0269), length: 25
000+00:05:36.107 T 90: [emsesp] thermostat(0x10) -W-> Me(0x0B), RC300Holiday1(0x0269), data: 18 05 02 18 05 02 02 11
000+00:05:37.294 T 100: [emsesp] thermostat(0x10) -B-> All(0x00), RC300Holiday1(0x0269), data: 18 05 02 18 05 02 02 11
000+00:05:37.603 T 101: [emsesp] controller(0x09) -W-> thermostat(0x10), RC300Holiday1(0x0269), data: 12 01 01 12 01 01 00 11
000+00:05:37.857 T 106: [emsesp] thermostat(0x10) -B-> All(0x00), RC300Holiday1(0x0269), data: 12 01 01 12 01 01 02 11

**Comment by mattfro** [comment] 2024-05-04 12:01
Seems it was much easier on mine that the other ticket you had. :)

**Comment by mattfro** [comment] 2024-05-05 11:17
@MichaelDvP now when it works, shall we close this ticket?

**Comment by proddy** [comment] 2024-05-05 11:24
yes, if you've confirmed it's working

**Closed** 2024-05-05 11:32 UTC
Labels: enhancement
